name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: "⬇️ Checkout"
      uses: actions/checkout@v2
    - name: "🔎 Linting"
      uses: norio-nomura/action-swiftlint@3.2.1
    - name: "🧪 Build & Tests"
      run: xcodebuild test -scheme SwiftDown -destination platform="macOS" -enableCodeCoverage YES
    - name: "📊 Upload coverage to Codecov"
      uses: codecov/codecov-action@v1.3.1
